### ISSUE TITLE
请问下为什么设置默认的选中咧弹出层并没有正确的展示？pickerValueDefault这个变量无效么

### ISSUE THREAD

**Issue by supremeJY** [MPComponent/mpvue-picker#15]
请问下为什么设置默认的选中咧弹出层并没有正确的展示？pickerValueDefault这个变量无效么？
![image](https://user-images.githubusercontent.com/33109486/46779914-8c4f0e80-cd4c-11e8-9b5b-33ac0e1fd8e8.png)
![image](https://user-images.githubusercontent.com/33109486/46779923-98d36700-cd4c-11e8-850e-0bedebd357e6.png)

**Comment by KuangPF** [comment]
参考 #16

**Comment by KuangPF** [comment]
如果需要使用城市选择器的话，建议使用 [mpvue-citypicker](https://github.com/MPComponent/mpvue-citypicker)
