### ISSUE TITLE
弹开出不来报以下错误

### ISSUE THREAD

**Issue by r1005410078** [MPComponent/mpvue-picker#22]
Template "471d0571" not found.
  143 |       </view>
  144 |     </view>
> 145 |     <template ref="mpvuePicker" bindonChange="handleProxy" bindonConfirm="handleProxy" bindonCancel="handleProxy" data-eventid="{{'6'}}" data-comkey="{{$k}}" data="{{...$root[$kk+'0'], $root}}" is="471d0571"></template>
      |                                                                                                                                                                                                      ^
  146 |   </view>
  147 | </template>

**Comment by KuangPF** [comment]
这个描述的不太清楚吧，我这边无法复现你这个问题。能否描述地详细点，贴上比较重要的代码。
