### ISSUE TITLE
老铁 安卓设备为什么显示的是原生控件？

### ISSUE THREAD

**Issue by 18706789739** [MPComponent/mpvue-picker#23]

**Comment by 18706789739** [comment]
可以设置不用原生吗

**Comment by KuangPF** [comment]
mpvue-picker 封装的原生 [picker-view](https://developers.weixin.qq.com/miniprogram/dev/component/picker-view.html) 组件，不是原生的 picker 组件，不知道你指的原生控件是不是原生的 picker 组件，如果显示的是原生的 picker 组件，可以看下组件名是不是使用了picker 保留字，如果排除了上诉原因，那么请提供下 mpvue 版本号和 mpvue-picker 版本号，以及相关的代码，方便排查问题。
