### ISSUE TITLE
从dcloud插件市场，下载运行，弹出show报错

### ISSUE THREAD

**Issue by RobinGitHub** [MPComponent/mpvue-picker#24]
`this.$refs.mpvuePicker.show is not a function. (In 'this.$refs.mpvuePicker.show()', 'this.$refs.mpvuePicker.show' is undefined); `
请问报这个错误是什么问题呢？

**Comment by KuangPF** [comment]
能否提供一下详细的使用代码，包括编辑器信息这些。

**Comment by RobinGitHub** [comment]
使用的工具是Hbuilder X 最新版，我从dcloud插件市场下载的文件放入components目录中，
然后按照示例 ![image](https://user-images.githubusercontent.com/3375920/54000553-cea53c00-4182-11e9-9c4c-73cd044bc9e9.png)粘贴复制，执行后就提示以下错误




this.$refs.mpvuePicker.show is not a function;at pages/login/login page handleProxy function    
TypeError: this.$refs.mpvuePicker.show is not a function    
at Vue$3.bindLogin (uni-app:///pages/login/login.vue?vue&type=script&lang=js&?01f1:143:30)    
at Array.boundFn (D:/HBuilderX/plugins/uniapp-cli/node_modules/@dcloudio/vue-cli-plugin-uni/packages/mpvue/index.js:249:63)    
 (D:/HBuilderX/plugins/uniapp-cli/node_modules/@dcloudio/vue-cli-plugin-uni/packages/mpvue/index.js:5550:40)    
at e.handleProxy (D:/HBuilderX/plugins/uniapp-cli/node_modules/@dcloudio/vue-cli-plugin-uni/packages/mpvue-page-factory/index.js:76:24)

**Comment by KuangPF** [comment]
我从插件市场下载，做了一个简单的测试，引入了 [src/pages/demo/index.vue](https://github.com/MPComponent/mpvue-picker/blob/master/src/pages/demo/index.vue)中的示例代码，改了下 `mpvue-picker` 的引入方式，即以 `dcloud` 插件的方式引入，其他地方没变，如下：
``` js
import mpvuePicker from '@/components/mpvue-picker/mpvuePicker.vue';
```
并没有复现问题，测试了微信小程序和浏览器都能正常工作。
<img width="1676" alt="issues-24-01" src="https://user-images.githubusercontent.com/20694238/54067887-96842300-4280-11e9-9ed3-5e99c942fa42.png">

<img width="1674" alt="issues-24-02" src="https://user-images.githubusercontent.com/20694238/54067870-7c4a4500-4280-11e9-93ff-93bf76cd515e.png">

你可以尝试在 HBuilderX 运行一下本仓库里面的 [demo](https://github.com/MPComponent/mpvue-picker/blob/master/src/pages/demo/index.vue),改一下插件的引入就可以了，看能不能正常运行。

除此之外，你还可以直接通过 npm 的安装方式引入 `mpvue-picker`，并在 HBuilderX 中使用，使用方法和 `mpvue` 的语法一样，可参考 readme。

**Comment by RobinGitHub** [comment]
好的，谢谢，我再试一下

**Comment by shenzhuan** [comment]
h5没有问题，小程序报错 Cannot read property 'show' of undefined; [Component] Event Handler Error @ pagesU/address/addressManage#handleEvent

**Comment by shenzhuan** [comment]
@RobinGitHub
