### ISSUE TITLE
使用picker  mode为selector并且多次调用时   pickerValueDefault改变，视图不更新

### ISSUE THREAD

**Issue by wjw-gavin** [MPComponent/mpvue-picker#25]
使用picker  mode为selector并且多次调用时   pickerValueDefault改变，视图不更新

**Comment by KuangPF** [comment]
`pickerValueDefault` 是初始化组件的时候才会生效，如果组件注册后再调用是不会生效的。

**Comment by SweetJun** [comment]
@KuangPF    想请教一下，如果同一个页面多个项需要调用，怎么实现每次打开都是默认当前点击的值呢。。

**Comment by KuangPF** [comment]
每个使用的地方都单独使用一个 `picker` 试下呢，这样每个 pciekr 都是独立的，不会互相影响。

**Comment by SweetJun** [comment]
@KuangPF    我这里是一个订单列表页，数量可以很多额，每个订单都可以操作picker，这样好像不太适用把。。。。

**Comment by KuangPF** [comment]
这个功能目前还不支持，如果页面性能不做严格要求的化，解决方式可以是每次点击的时候给 `pickerValueArray` 重新赋值，因为当检测到 `pickerValueArray` 发生变化时，会重新渲染 `picker`。
