### ISSUE TITLE
IOS12.2 苹果8出现bug？

### ISSUE THREAD

**Issue by JKD128KKK** [MPComponent/mpvue-picker#28]
![firstClick](https://user-images.githubusercontent.com/39514394/57265697-6b188b80-70ab-11e9-879d-5526066ce208.jpg)

![slideDown](https://user-images.githubusercontent.com/39514394/57265684-65bb4100-70ab-11e9-9eb2-5f136218e40e.jpg)

**Comment by KuangPF** [comment]
能否提供下`mpvue-picker`版本号以及调用的相关代码呢

**Comment by JKD128KKK** [comment]
`<div class="divPicker" style="margin-left:30rpx;display:flex;" @click="showPicker">
                <div>
                {{assigneeArray[assigneeIndex].label}}
                </div>
                <i  class="iconfont icon-triangledownfill" ></i>
</div>
 <mpvue-picker ref="mpvuePicker" 
              :mode="mode" 
              :pickerValueDefault="assigneeDefault" 
              @onChange="onChange" 
              @onConfirm="onConfirm" 
              @onCancel="onCancel" 
              :pickerValueArray="assigneeArray">
 </mpvue-picker>
 .divPicker{
    width:170rpx;
    height:50rpx;
    line-height:40rpx;
    border:2rpx solid #FFA54F;
    color:#FFA54F;
    border-radius:10rpx;
    text-align:center;
  }
`基本上就是贴的第一个demo
![版本号"mpvue-picker": "^2.1.0","mpvue": "^2.0.0",](https://user-images.githubusercontent.com/39514394/57266253-c8add780-70ad-11e9-8dfd-d6230dc66170.png)

**Comment by JKD128KKK** [comment]
小程序工具打开是没有问题的 真机的时候就出问题了

**Comment by JKD128KKK** [comment]
而且安卓机是没有问题的

**Comment by KuangPF** [comment]
你用真机调试下呢，看下数据渲染出来没，我这边用 iphone8， ios 12.2 跑了一下仓库的 [demo](https://github.com/MPComponent/mpvue-picker/blob/master/src/pages/demo/index.vue)，没有出现类似的问题。

**Comment by JKD128KKK** [comment]
好吧 我也试了仓库的demo 没问题

**Comment by JKD128KKK** [comment]
原因是 我将mpvue-picker放在scroll-view里

**Comment by KuangPF** [comment]
找到原因就行。
