### ISSUE TITLE
直接复制mpvue-picker.vue代码到项目，uni-app编译到手机上报错

### ISSUE THREAD

**Issue by zhengxueqi** [MPComponent/mpvue-picker#29]
报一大堆错误 可能和es6之类的转译有关。Hello uni-app 项目中的这个组件复制引用没问题

**Comment by KuangPF** [comment]
`mpvue-picker.vue` 为插件的源文件，你可以运行下项目中的 demo，参考：https://github.com/MPComponent/mpvue-picker/issues/24#issuecomment-471154977

**Comment by zhengxueqi** [comment]
好的。所以还是用Hello项目中的现成的组件为好。
