### ISSUE TITLE
一列的时候有问题

### ISSUE THREAD

**Issue by jane-** [MPComponent/mpvue-picker#3]
一列的时候，点击确定一直关闭不了pickerConfirm事件没有触发

**Comment by KuangPF** [comment]
我这边测试了一下，暂时没有复现你说的问题，你方便提供一下代码不，这边看能不能排查出问题。

**Comment by DevinWell1ee** [comment]
@pickerConfirm改为@onConfirm
他抛的事件是onConfirm

**Comment by Lillian0** [comment]
改成 onConfirm 没有关闭控制。
