### ISSUE TITLE
取消又显示的问题

### ISSUE THREAD

**Issue by Bright2017** [MPComponent/mpvue-picker#30]
小程序使用在多级联动的时候，点击取消按钮弹出窗会重新显示出来，关闭不了

**Comment by KuangPF** [comment]
能否提供下代码片段，或者参考 [demo](https://github.com/MPComponent/mpvue-picker/blob/master/src/pages/demo/index.vue#L1)

**Comment by Bright2017** [comment]
`<div class="weui-cell">
          <div class="weui-cell__hd">
            <label for class="weui-label">职能：</label>
          </div>
          <div class="weui-cell__bd"  @click="showJob">
            <input class="weui-input" type="text" placeholder="请选择职能" v-model="job">
            <mpvue-picker
              ref="mpvuePicker"
              mode="multiLinkageSelector"
              :deepLength=3
              :pickerValueDefault="jobIndex"
              @onConfirm="JobConfirm"
              @onCancel="JobCancel"
              :pickerValueArray="jobList"
            ></mpvue-picker>
          </div>
        </div>`
data(){}里面的数据
`// 职能
      jobIndex: [],
      jobList: [
        {
          label: "phone",
          value: 0,
          children: [
            {
              label: "iphone",
              value: 1,
              children: [
                {
                  label: "iphoneX",
                  value: 1
                },
                {
                  label: "iphone8",
                  value: 2
                },
                {
                  label: "iphone8 Plus",
                  value: 3
                }
              ]
            },
            {
              label: "android",
              value: 1,
              children: [
                {
                  label: "vivo",
                  value: 1
                },
                {
                  label: "魅族",
                  value: 2
                },
                {
                  label: "小米",
                  value: 3
                }
              ]
            }
          ]
        },
        {
          label: "PC",
          value: 0,
          children: [
            {
              label: "mac",
              value: 1,
              children: [
                {
                  label: "macbook Pro",
                  value: 1
                },
                {
                  label: "iMac",
                  value: 2
                },
                {
                  label: "mackbook",
                  value: 3
                },
                {
                  label: "mackbook air",
                  value: 3
                }
              ]
            },
            {
              label: "windows",
              value: 1,
              children: [
                {
                  label: "dell",
                  value: 1
                },
                {
                  label: "surface",
                  value: 2
                },
                {
                  label: "thinkpad",
                  value: 3
                }
              ]
            }
          ]
        }
      ],
      job: "",`
函数
`// 选择职能
    showJob(){
      this.$refs.mpvuePicker.show();
    },
    JobConfirm(e){
      console.log("确定",e);
       this.job = e.label;
    },
    JobCancel(e){
      console.log("取消",e);
    },`

**Comment by Bright2017** [comment]
我查到的是show()函数在执行取消和确定后会再执行一次，但是我不知道从哪里执行

**Comment by KuangPF** [comment]
建议你先写个简单的 `picker` 试下，然后再排查一下问题所在。

**Comment by Bright2017** [comment]
找到问题了，点击事件显示弹窗的是放在父级，改成在同一级的元素就可以了
