### ISSUE TITLE
mode为dateSelector时的问题

### ISSUE THREAD

**Issue by boxshadow** [MPComponent/mpvue-picker#31]
在uni-app中开发小程序时,
通过第一个单列picker的某一个选项confirm后,在当前picker上设置mode="dateSelector", 然后调用ref的show方法,
这个时候无论设置默认的值是 new Date(2019,5,15)/[2019,5,15]还是不设置都呈现出下图所属的内容
请教一下是什么问题, 代码有点乱 showDatePicker 这个方法就是打开日期选择器的方法
<img width="475" alt="WX20190515-031111@2x" src="https://user-images.githubusercontent.com/8577474/57725186-27331100-76bf-11e9-9730-62820fbc743d.png">
代码块是这样的
`<template>`
    `<mpvue-picker @onConfirm="timeConfirmed" :pickerValueDefault="[0]" ref="mpvuePicker" :mode="picker.mode" :pickerValueArray="picker.pickerValueArray">` 
   `</mpvue-picker>`
`</template>`
`<script>`

`data: () => ({
    picker: {
	mode: null,
	pickerValueArray: null,
    }
}),`

`method: {`
  `showSinglePicker() {`
    `this.$set(this, 'picker', {mode: 'selector', pickerValueArray: timesFormat})`
    `this.$refs.mpvuePicker.show();`
`},`

`showDatePicker() {`
 `this.$set(this, 'picker', {mode: 'dateSelector', pickerValueDefault: [2019,5,15]});`
`this.$refs.mpvuePicker.show();`
`},`

`timeConfirmed({index:{[0]: index}, label, value: {[0]: value}}) {
	const {times} = this;
	const source = times.find(item => (item.id === value));
	if(source) {
	    this.$set(this.form, 'time', value)
	    if (source.key === 'specified') {
		setTimeout(() => {
			this.showDatePicker();
		}, 3000)
	    } else {
		this.$set(this.form, 'date', null)
	    }
	} else {
            console.log(value);
       }				
   }
}
`

**Comment by KuangPF** [comment]
参考下仓库 demo 呢：
https://github.com/MPComponent/mpvue-picker/blob/d0317a1383d4be04b91f40c4b37aa7f670da9249/src/pages/demo/index.vue#L1-L316

**Comment by zhiyicx** [comment]
我是参考的demo

**Comment by boxshadow** [comment]
> 参考下仓库 demo 呢：
> https://github.com/MPComponent/mpvue-picker/blob/d0317a1383d4be04b91f40c4b37aa7f670da9249/src/pages/demo/index.vue#L1-L316

已经是参考这个demo来的，而且单独使用dateSelector也不行，没有编译报错，没有运行报错，就和图上的样子一样

**Comment by KuangPF** [comment]
我这边使用 `uni-app` 和使用 `mpvue` 运行了仓库 demo，都没有报错
<img width="1676" alt="mpvue-picker-issues31" src="https://user-images.githubusercontent.com/20694238/57745639-90874400-7700-11e9-8627-5094f759d9c5.png">
<img width="1669" alt="mpvue-picker-issues31-02" src="https://user-images.githubusercontent.com/20694238/57745791-160af400-7701-11e9-9804-0ba0c745f1b1.png">

你那边运行仓库 demo 能正常显示不呢，如果没有出现上诉情况，那就只有一点一点排查业务代码了。

**Comment by boxshadow** [comment]
> 我这边使用 `uni-app` 和使用 `mpvue` 运行了仓库 demo，都没有报错
> <img alt="mpvue-picker-issues31" width="1676" src="https://user-images.githubusercontent.com/20694238/57745639-90874400-7700-11e9-8627-5094f759d9c5.png">
> <img alt="mpvue-picker-issues31-02" width="1669" src="https://user-images.githubusercontent.com/20694238/57745791-160af400-7701-11e9-9804-0ba0c745f1b1.png">
> 
> 你那边运行仓库 demo 能正常显示不呢，如果没有出现上诉情况，那就只有一点一点排查业务代码了。

很奇怪的现象, demo代码原封不动得运行, 除了日期选择器之外, 所有的picker都运行正常
<img width="394" alt="WX20190517-225315@2x" src="https://user-images.githubusercontent.com/8577474/57936547-c726af80-78f6-11e9-84aa-3ee99e6b40a3.png">

**Comment by KuangPF** [comment]
你方便把能稳定复现 bug 的完整代码，`mpvue-picker` 版本，以及 uni-app 版本（HBuilderX 的版本）发我邮箱下不，我这边定位下具体的问题，邮箱：kuangpf1995@gmail.com。

**Comment by boxshadow** [comment]
> 你方便把能稳定复现 bug 的完整代码，`mpvue-picker` 版本，以及 uni-app 版本（HBuilderX 的版本）发我邮箱下不，我这边定位下具体的问题，邮箱：[kuangpf1995@gmail.com](mailto:kuangpf1995@gmail.com)。

已发邮件

**Comment by KuangPF** [comment]
问题原因是由于使用了 uni-app 扩展市场中 [mpvue-picker](https://ext.dcloud.net.cn/plugin?id=115) 插件，但那个插件不是我在维护，因此不是最新版，所以就有上述问题。在 uni-app 使用的话建议用 npm 的方式安装，这样可以保证是最新版。
