### ISSUE TITLE
[BUG] dateSelector 模式第一次加载出错

### ISSUE THREAD

**Issue by brucehelen** [MPComponent/mpvue-picker#34]
```javascript
this.currentColumnTitle = '生日'
this.pickerValueDefault = new Date('2000-01-01')
this.pickerValueArray = []
this.pickerMode = 'dateSelector'
this.$refs.mpvuePicker.show()
```

第一次加载提示：
```
Cannot read property 'label' of undefined; [Component] Event Handler Error @ node-modules/mpvue-picker/src/mpvue-picker/mpvuePicker#handleEvent
```

![image](https://user-images.githubusercontent.com/5308436/59175985-29876e80-8b8a-11e9-869d-5c2bed23d15e.png)

出错详情

![image](https://user-images.githubusercontent.com/5308436/59176005-3b691180-8b8a-11e9-9d2b-d956090424fa.png)

**Comment by KuangPF** [comment]
`mpvue-picker` 版本号是多少，`dateSelector` 模式是在 2.1.0 以后支持的。

**Comment by brucehelen** [comment]
使用的最新的`2.1.1`版本

使用提供的demo测试，在iPhone 7可以测试出来
![image](https://user-images.githubusercontent.com/5308436/59183529-c5bb7080-8b9e-11e9-9270-92673c218a39.png)

**Comment by brucehelen** [comment]
补充错误截图

![image](https://user-images.githubusercontent.com/5308436/59183723-28147100-8b9f-11e9-9524-fb7712b7a0ec.png)

**Comment by KuangPF** [comment]
2.1.2 版本修复了，是 `new Date` 的一个 bug，如果设置的默认值为日期类型应该不会有问题吧。

**Comment by brucehelen** [comment]
可以了，谢谢
