### ISSUE TITLE
在页面底部可以看到确定取消按钮

### ISSUE THREAD

**Issue by webVictor** [MPComponent/mpvue-picker#35]
用力拉页面，在页面底部可以看到确定取消按钮

**Comment by KuangPF** [comment]
应该是 ios 的惯性拉动，安装下最新版本 2.1.3。

**Comment by FuXi-Ranger** [comment]
动态改变级联菜单数据 怎么样才能实时刷新呢  我是在onchange发起新的数据请求更新数据节点
