### ISSUE TITLE
能在pickerCancel方法里emit一个事件出来么？

### ISSUE THREAD

**Issue by DevinWell1ee** [MPComponent/mpvue-picker#4]
因为页面有textarea组件，它的层级是最高的（在该picker的层级之上），所以我需要动态控制其展示否。
所以当点取消和点mask的时候能否抛个事件？

**Comment by KuangPF** [comment]
可以，下次迭代就加上了这个事件，如果你现在这个需求比较急的话，你可以自己先自改一下源码，添加一个pickerCancel 事件。

**Comment by KuangPF** [comment]
v2.0.1 已支持

**Comment by KuangPF** [comment]
你是怎样调用的 pickerCancel ，方便提供一下代码不

**Comment by Renford** [comment]
@KuangPF 这用调用有问题吗

```
  onUnload () {
    console.log('关闭日历....onUnload', this.$refs)
    this.$refs.mpvuePicker.pickerCancel()
  }
```

**Comment by KuangPF** [comment]
我测试了下，在 onUnload 里面调用 pickerCancel 方法，然后再次进入页面显示正常，不知道方不方便提供一下更多的代码，好排查问题。
![issues 4](https://user-images.githubusercontent.com/20694238/45628909-b56edd00-bac7-11e8-9956-fdde61ef12cc.gif)

**Comment by Renford** [comment]
不好意思，那个是公司项目。
用最新mpvue-quickstart新建了一个项目（老项目是俩个月之前创建的），将老工程源代码考进去，就可以了，具体为啥还不清楚。
其实，这段时间mpvue-quickstart只是更新了下mpvue-loader，从1.0.12升级到1.1.2。

**Comment by Renford** [comment]
终于知道是啥问题了，跟详情页数据不会重置的解决方案（如下所示）冲突了。
```
Vue.mixin({
  onUnload () {
    if (this.$options.data) {
      this._watchers = []
      this._watcher.teardown()
      Object.assign(this, this.$options.data)
    }
  }
})
```
