### ISSUE TITLE
做省市联动很卡

### ISSUE THREAD

**Issue by yeyifen** [MPComponent/mpvue-picker#6]
用这做了个中国的省市联动，卡的不要不要的，有没解决办法？

**Comment by KuangPF** [comment]
因为联动需要循环，第一级或者第二级改变都需要遍历一遍数组，省市可能数据量比较大，然后就出现了卡顿，不知道你是在什么机型上测试的，不过按道理来讲的话，应该也不会卡的不要不要的吧...如果真是这样，那就看这边能不能优化下。

**Comment by yeyifen** [comment]
抱歉，描述得有点粗糙，重现的情况是这样的：在一个界面，用了这个插件，同时还存在其他input输入框的时候，这个插件本身不卡，但在input输入框快速输入或删除时，肉眼可见的卡。目前我这边做测试的机型有835 cpu、8G内存的小米手机，还有iPhone X，都是一样。

**Comment by KuangPF** [comment]
已将 citypicker 单独出来，改变了城市数据结构，没有出现卡顿现象 [mpvue-citypicker](https://github.com/MPComponent/mpvue-citypicker)
