### ISSUE TITLE
3级联动问题～

### ISSUE THREAD

**Issue by DevinWell1ee** [MPComponent/mpvue-picker#7]
比如：当第二级滑动第5个，然后我第一级换一个，此时默认第二级还是默认在第5个，但是当第一级的children没有5个时～会报错啦。

我觉得当哪一级发生变化的时候，它的下级都应该初始化到默认第一个吧

**Comment by DevinWell1ee** [comment]
我也发现当全国的联动的时候，确实很卡，还会影响其他的表单控件

**Comment by KuangPF** [comment]
v2.0.1  已修复
