### ISSUE TITLE
单列时数组数据结构问题

### ISSUE THREAD

**Issue by gin280** [MPComponent/mpvue-picker#8]
如果数据结构为
pickerValueArray: [
        { label: "住宿费", value: "a" },
        { label: "礼品费", value: "b" },
        { label: "活动费", value: "c" }
     ]时组件该怎么设置

**Comment by KuangPF** [comment]
目前单列和多列不支持键值对，如果是单列的话数据结构为
``` javascript
pickerValueArray: ['住宿费', '礼品费', '活动费', '通讯费', '补助']
``` 
下次迭代会考虑使用键值对的形式

**Comment by KuangPF** [comment]
v2.0.1  已支持
